version: 2.1
jobs:
  build:
    docker:
      - image: returntocorp/sgrep-build:2.0
    steps:
      - checkout
      - run: eval $(opam env); ./configure -novisual && make depend && make

  test:
    docker:
      - image: returntocorp/sgrep-build:2.0
    steps:
      - checkout
      - run: export PFFF_HOME=/home/opam/project
      - run: eval $(opam env); ./configure -novisual && make depend && make && make test
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
      - test