version: 2.1
jobs:
  build:
    docker:
      - image: circleci/returntocorp/sgrep-build:1.0
    steps:
      - checkout
      - run: make
  test:
    docker:
      - image: circleci/returntocorp/sgrep-build:1.0
    steps:
      - checkout
      - run: make test
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
      - test