version: 2.1
jobs:
  build:
    docker:
      - image: returntocorp/sgrep-build:1.0
    steps:
      - checkout
      - run: opam install pfff
      - run: cd pfff
      - run: ./configure -novisual
      - run: make depend
      - run: make
  test:
    docker:
      - image: returntocorp/sgrep-build:1.0
    steps:
      - checkout
      - run: make test
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build