name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install System Deps
      run: sudo apt-get update && apt-get install -y --no-install-recommends m4 perl wget swi-prolog mercurial opam
    - name: Install pfff
      run: |
        git pull && opam update && opam switch 4.07 && \
        opam install ocaml-migrate-parsetree ocaml-migrate-parsetree.1.3.1 && \
        opam install pfff
    - name: Run Test
      run: eval $(opam env); ./configure -novisual && make depend && make test
