name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install System Deps
      run: sudo apt-get update && sudo apt-get install -y --no-install-recommends m4 perl wget swi-prolog mercurial opam
    - name: Install pfff
      run: opam init && opam switch 4.07 && opam install ocaml-migrate-parsetree ocaml-migrate-parsetree.1.3.1 && opam install pfff
    - name: Run Tests
      run: eval $(opam env); ./configure -novisual && make depend && make test
